import { pgTable, serial, text, integer, numeric, boolean, jsonb, bigint } from 'drizzle-orm/pg-core';

export const paymentAccounts = pgTable('payment_accounts', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  accountType: text('account_type').notNull(),
  provider: text('provider').notNull().default(''),
  currency: text('currency').notNull().default('NPR'),
  openingBalance: numeric('opening_balance', { precision: 12, scale: 2 }).notNull().default('0'),
  accountNumber: text('account_number').notNull().default(''),
  branch: text('branch').notNull().default(''),
  active: boolean('active').notNull().default(true),
  notes: text('notes').notNull().default(''),
  createdBy: integer('created_by'),
  updatedBy: integer('updated_by'),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
  updatedAt: bigint('updated_at', { mode: 'number' }).notNull(),
});

export const paymentTransactions = pgTable('payment_transactions', {
  id: serial('id').primaryKey(),
  transactionId: text('transaction_id').notNull(),
  providerTransactionId: text('provider_transaction_id').notNull().default(''),
  orderId: integer('order_id'),
  customOrderId: integer('custom_order_id'),
  invoiceRef: text('invoice_ref').notNull().default(''),
  customerId: integer('customer_id'),
  customerName: text('customer_name').notNull().default(''),
  paymentAccountId: integer('payment_account_id'),
  channel: text('channel').notNull(),
  paymentMethod: text('payment_method').notNull().default(''),
  amount: numeric('amount', { precision: 12, scale: 2 }).notNull(),
  currency: text('currency').notNull().default('NPR'),
  processingFee: numeric('processing_fee', { precision: 12, scale: 2 }).notNull().default('0'),
  netAmount: numeric('net_amount', { precision: 12, scale: 2 }).notNull().default('0'),
  taxAmount: numeric('tax_amount', { precision: 12, scale: 2 }).notNull().default('0'),
  status: text('status').notNull().default('initiated'),
  intent: text('intent').notNull().default(''),
  transactionType: text('transaction_type').notNull().default('payment'),
  initiatedAt: bigint('initiated_at', { mode: 'number' }).notNull(),
  completedAt: bigint('completed_at', { mode: 'number' }),
  settlementAt: bigint('settlement_at', { mode: 'number' }),
  failureReason: text('failure_reason').notNull().default(''),
  refundRef: text('refund_ref').notNull().default(''),
  reconciliationStatus: text('reconciliation_status').notNull().default('unreconciled'),
  source: text('source').notNull().default(''),
  audit: jsonb('audit').$type<Record<string, unknown>[]>().notNull().default([]),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
  updatedAt: bigint('updated_at', { mode: 'number' }).notNull(),
});

export const paymentProviderEvents = pgTable('payment_provider_events', {
  id: serial('id').primaryKey(),
  provider: text('provider').notNull(),
  eventId: text('event_id').notNull().unique(),
  eventType: text('event_type').notNull(),
  transactionId: text('transaction_id').notNull().default(''),
  payload: jsonb('payload').$type<Record<string, unknown>>().notNull().default({}),
  processed: boolean('processed').notNull().default(false),
  processedAt: bigint('processed_at', { mode: 'number' }),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
});

export const paymentRefunds = pgTable('payment_refunds', {
  id: serial('id').primaryKey(),
  transactionId: integer('transaction_id').notNull(),
  refundRef: text('refund_ref').notNull().default(''),
  amount: numeric('amount', { precision: 12, scale: 2 }).notNull(),
  reason: text('reason').notNull().default(''),
  type: text('type').notNull().default('full_refund'),
  status: text('status').notNull().default('requested'),
  chargeback: boolean('chargeback').notNull().default(false),
  initiatedBy: integer('initiated_by'),
  approvedBy: integer('approved_by'),
  journalEntryId: integer('journal_entry_id'),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
  processedAt: bigint('processed_at', { mode: 'number' }),
});

export const paymentReconciliations = pgTable('payment_reconciliations', {
  id: serial('id').primaryKey(),
  paymentAccountId: integer('payment_account_id').notNull(),
  periodStart: bigint('period_start', { mode: 'number' }).notNull(),
  periodEnd: bigint('period_end', { mode: 'number' }).notNull(),
  openingExternalBalance: numeric('opening_external_balance', { precision: 12, scale: 2 }).notNull().default('0'),
  closingExternalBalance: numeric('closing_external_balance', { precision: 12, scale: 2 }).notNull().default('0'),
  status: text('status').notNull().default('in_progress'),
  notes: text('notes').notNull().default(''),
  createdBy: integer('created_by'),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
  lockedAt: bigint('locked_at', { mode: 'number' }),
});

export const paymentReconciliationItems = pgTable('payment_reconciliation_items', {
  id: serial('id').primaryKey(),
  reconciliationId: integer('reconciliation_id').notNull(),
  transactionId: integer('transaction_id'),
  externalRef: text('external_ref').notNull().default(''),
  externalAmount: numeric('external_amount', { precision: 12, scale: 2 }).notNull().default('0'),
  matched: boolean('matched').notNull().default(false),
  matchType: text('match_type').notNull().default(''),
  discrepancy: numeric('discrepancy', { precision: 12, scale: 2 }).notNull().default('0'),
  status: text('status').notNull().default('unmatched'),
  notes: text('notes').notNull().default(''),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
});
